---
title: R en Linux
date: 2015-05-06
tags: ["R", "RStudio", "Linux"]
comments: true
share: true
draft: true
---

Hola muchachada.

Hoy la palangana viene repleta de... paquetes de `R`, y por si fuera poco atractivo para cualquier alma de cántaro, paquetes de `R` en Linux.

Resulta que acabo de actualizar unos paquetes de `R` y se  me ha ocurrido escribir un poco al respecto. No me gusta abarcar más de lo que me corresponde, así que solo voy a explicar cómo actualizar el programa de forma automática, y cómo sorteo alguna que otra incomodidad de la instalación y actualización de paquetes

## Instalar y actualizar R de forma automática

Para instalar o mantener actualizado `R` de manera automática hay que realizar unos sencillos pasos que dependen de la distro de Linux que estés utilizando. Por ejemplo, si usas, como tantísima gente, Ubuntu, [tienes unas instrucciones muy claras](http://cran.r-project.org/bin/linux/ubuntu/README):

1. Edita el archivo `sources.list` con tu editor favorito. En una terminal: `sudo atom /etc/apt/sources.list`.
2. Añade una entrada en el archivo con el URL del *mirror* de CRAN preferido, mediante `deb https://cloud.r-project.org/bin/linux/ubuntu/ xenial/`, cambiando `xenial` por la versión que estés usando (_trusty_, _precise_, _yakkety_ o cualquier otro nombre chorra).
3. Guarda el documento y ejecuta el clásico `sudo apt-get update && sudo apt-get upgrade` si ya tuvieras `R` instalado, o `sudo apt-get install r-base-dev` si vas a instalarlo en ese momento (te recomiendo la versión _dev_).
4. Por último, queda añadir la clave para la certificación de paquetes instalados con `sudo apt-key adv –keyserver keyserver.ubuntu.com –recv-keys E084DAB9`.

Hay otras distros con un patrón de instalación mucho más sencillo: por ejemplo, ahora mismo soy usuario de una variante de [Arch Linux](https://www.archlinux.org/), y gracias a [AUR](https://aur.archlinux.org/) se puede instalar en un segundo. Arch Linux tiene la ventaja de ser una distro *Rolling Release*, lo que implica que no hay que cambiar de versión cada año o así, reinstalando toda la retahíla de programas una y otra vez.

## Instalar y actualizar librerías

Desde que comencé a utilizar Linux me di cuenta de algo que ocurría con las librerías de `R`, no solo es que haya que identificarse como superusuario a la hora de instalar el propio programa (de forma que las librerías que acompañan a `R` por defecto se instalan en el directorio `/usr/lib/R/library`, aunque hay formas de sortear este punto), sino que los paquetes se instalan en plan *source*, de forma que no viene nada precompilado, incluyendo alguna dependencia de software (por ejemplo, prueba a instalar el paquete `rgeos` sin más y verás lo que pasa...).

Respecto al primer punto, en principio esto es una ventaja independientemente de que se trate de una máquina personal o compartida por varios usuarios donde más de uno utilice `R`. Lo único es que, si quieres actualizar a mano los paquetes y eso incluye a alguno de los paquetes básicos, si se inicia la aplicación sin permisos de superusuario, las librerías se instalarán por defecto en el directorio del usuario que haya abierto la sesión (en principio este será `/home/pepitoflores/R/x86_64-pc-linux-gnu-library/version-de-R-que-uses`), y a la hora de actualizar las librerías que requieren permisos (las que están instaladas en `/usr/lib/R/library`), la consola nos devolverá un error. Esto se puede sortear de dos formas:

1. abriendo `R` como superusuario y actualizando los paquetes (`update.packages()`) o,
2. esperando a que se actualicen esos paquetes dentro del repositorio que empleamos para instalar el propio `R`.

En relación al segundo punto, la verdad es que no hay una salida fácil: solo queda leer la documentación de los paquetes y ver posibles dependencias externas (algo habitual, por ejemplo, con los paquetes de estadística espacial), ver por dónde peta al instalarlo, y buscar e instalar los paquetes necesarios.


## Últimos apuntes

Si trabajas en varios proyectos y te preocupa llevar un control de las librerías necesarias para correr un *script* y aumentar así el nivel de reproducibilidad, prueba a utilizar la libraría [`packrat`](https://rstudio.github.io/packrat/ "packrat"). Esto viene muy bien para tener un proyecto autosuficiente, con lo que el código que hace seis meses funcionó, hoy también funcionará.

Por ahora eso es todo. Pasa un buen día. :)
